config:
  SECRET_ARN: arn:aws:secretsmanager:us-east-1:145722906259:secret:rds-db-credentials/cluster-O4PBAPYVBKV3R6VRGZYHSAV3II/MasterUsername-D19rwD
  DB_ARN: arn:aws:rds:us-east-1:145722906259:cluster:nihongo-service-test-rdscluster-1tzaabcl5ujl
  DATABASE_NAME: RANDOMNAME
