service:
  name: nihongo-service

provider:
  name: aws
  runtime: nodejs10.x
  stackName: ${self:service}-${self:provider.stage}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: "*"
  environment:
    SECRET_ARN: ${ssm:/${self:provider.stage}-${self:service}-SECRET_ARN~true}
    DB_ARN: ${ssm:/${self:provider.stage}-${self:service}-DB_ARN~true}
    DATABASE_NAME: ${ssm:/${self:provider.stage}-${self:service}-DATABASE_NAME~true}
    APOLLO_ENGINE_KEY: ${ssm:/${self:provider.stage}-${self:service}-APOLLO_ENGINE_KEY~true}

plugins:
  - serverless-offline

functions:
  graphql:
    handler: src/handler.handler
    timeout: 30
    events:
      - http:
          path: graphql
          method: post
          cors: true
          
resources:
  Resources:
    RDSCluster:
      Type: AWS::RDS::DBCluster
      Properties:
        MasterUsername: MasterUsername
        MasterUserPassword: MasterUserPassword
        DatabaseName: ${ssm:/${self:provider.stage}-${self:service}-DATABASE_NAME~true}
        Engine: aurora
        EngineMode: serverless
        ScalingConfiguration:
          AutoPause: true
          MaxCapacity: 16
          MinCapacity: 2
          SecondsUntilAutoPause: 3600