service:
  name: nihongo-service

provider:
  name: aws
  runtime: nodejs10.x
  stackName: ${self:service}-${self:provider.stage}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: "*"

custom:
  RDS:
    name: RANDOMNAME
  APIGateway:
    graphQL:
      path: /graphql

package:
  exclude:
    - src/**
    - node_modules/**

plugins:
  - serverless-offline

functions:
  graphql:
    handler: src/handler.handler
    timeout: 30
    events:
      - http:
          path: graphql
          method: post
          cors: true
    environment:
      SECRET_ARN:
        Ref: RDSSECRET
      DB_ARN:
        Ref: RDSCluster
      DATABASE_NAME: ${self:custom.RDS.name}
      APOLLO_ENGINE_KEY: ${ssm:/${self:provider.stage}-${self:service}-APOLLO_ENGINE_KEY~true}
          
resources:
  Resources:
    RDSSECRET:
      Type: "AWS::SecretsManager::Secret"
      Properties:
        Description: "This is a Secrets Manager secret for an RDS DB instance"
        GenerateSecretString:
          SecretStringTemplate: '{"username": "admin"}'
          GenerateStringKey: "password"
          PasswordLength: 16
          ExcludeCharacters: '"@/\'

    RDSCluster:
      Type: AWS::RDS::DBCluster
      Properties:
        MasterUsername:
          Fn::Join: ['', ['{{resolve:secretsmanager:', { "Ref": "RDSSECRET" }, ':SecretString:username}}' ]]
        MasterUserPassword:
          Fn::Join: ['', ['{{resolve:secretsmanager:', { "Ref": "RDSSECRET" }, ':SecretString:password}}' ]]
        DatabaseName: ${self:custom.RDS.name}
        Engine: aurora
        EngineMode: serverless
        ScalingConfiguration:
          AutoPause: true
          MaxCapacity: 16
          MinCapacity: 2
          SecondsUntilAutoPause: 3600

    #This is a SecretTargetAttachment resource which updates the referenced Secret resource with properties about
    #the referenced RDS instance
    RDSSecretInstanceAttachment:
      Type: "AWS::SecretsManager::SecretTargetAttachment"
      Properties:
        SecretId:
          Ref: RDSSECRET
        TargetId:
          Ref: RDSCluster
        TargetType: AWS::RDS::DBInstance